openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
tags:
  - name: bikes
    description: Operaciones con bicis
  - name: users
    description: Operaciones con usuarios
servers:
  - url: 'https://apibikes.com'
paths:
  /bikes:
    get:
      tags:
        - bikes
      summary: Devuelve bicis registradas.
      description: |
        Lista las bicis solicitadas segun filtros aplicados
        Permite filtrar mediante brand o model incluso ambos a la vez
          - brand: Filtra por marca
          - model: Filtra por modelo
      parameters:
        - name: brand
          in: query
          description: Filtro por marca de bici
          required: false
          schema:
            type: string
        - name: model
          in: query
          description: Filtro por modelo
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BikeOutDto'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /bikes/{bikeId}:
    get:
      tags:
        - bikes
      summary: Detalle de una bici
      description: Devuelve los detalles de una bici específica.
      parameters:
        - name: bikeId
          in: path
          description: Identificador de bici
          required: true
          schema:
            type: number
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/BikeOutDto'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - bikes
      summary: Elimina una bici
      description: Da de baja una bici cuyo id se para como parametro.
      parameters:
        - name: bikeId
          in: path
          description: Identificador de bici
          required: true
          schema:
            type: number
            format: int64
      responses:
        '204':
          description: No content
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
        - bikes
      summary: Modifica una bici
      description: Permite modificar detalles de una bici
      parameters:
        - name: bikeId
          in: path
          description: Identificador de bici
          required: true
          schema:
            type: number
            format: int64
      requestBody:
        description: Nuevos detalles de la bici
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BikeInDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BikeOutDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /users/{userId}/bikes:
    post:
      tags:
        - bikes
        - users
      summary: Registra una bici
      description: Da de alta una bici
      parameters:
        - name: userId
          in: path
          description: Identificador del usuario propietario de la bici
          required: true
          schema:
            type: number
            format: int64
      requestBody:
        description: Detalles de la nueva bici
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bike'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BikeOutDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /users:
    get:
      tags:
        - users
      summary: Devuelve listado de usuarios.
      description: |
        Lista los usuarios registrados segun filtros aplicados
        
        patapimpatapam
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserOutDto'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - users
      summary: Registra un usuario
      description: Detalles del nuevo usuario
      requestBody:
        description: Nuevos detalles de la bici
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              standarUser:
                value:
                  name: Pedro
                  surname: Perez
                  email: pepe@perez.com
                  birthDate: 1998-12-11
              premiumUser:
                value:
                  name: Mario
                  surname: Silvio
                  email: mario@mail.com
                  birthDate: 1998-02-11
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOutDto'
              examples:
                standarUser:
                  value:
                    id: 12
                    name: Pedro
                    surname: Perez
                    email: pepe@perez.com
                    birthDate: 1998-12-11
                premiumUser:
                  value:
                      id: 19
                      name: Mario
                      surname: Silvio
                      email: mario@mail.com
                      birthDate: 1998-02-11
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    Bike:
      type: object
      properties:
        brand:
          type: string
          description: Marca de bici
          example: Trek
        model:
          type: string
          description: Modelo de bici
          example: Caliber
        releaseDate:
          type: string
          format: date
          description: Fecha de lanzamiento
          example: 2021-09-20
        color:
          type: string
          description: Color cuadro bici
          example: Red
    BikeInDto:
      allOf:
        - $ref: '#/components/schemas/Bike'
        - type: object
          properties:
            registrationDate:
                type: string
                format: date
                description: Fecha de registro
                example: 2022-01-01
    BikeOutDto:
      allOf:
        - type: object
          properties:
            id:
              type: number
              format: int64
              description: Identificador de bici
              example: 1
            userId:
              type: number
              format: int64
              description: Identificador del propietario
              example: 8
        - $ref: '#/components/schemas/BikeInDto'
    User:
      type: object
      properties:
        name:
            type: string
            description: Nombre del usuario
        surname:
          type: string
          description: Apellido del usuario
        email:
          type: string
          description: Dirección de correo del usuario
        birthDate:
          type: string
          format: date
          description: Fecha cumpleaños del usuario
      example:
        name: Pedro
        surname: Perez
        email: pepe@perez.com
        birthDate: 1998-12-11
    UserInDto:
      allOf:
        - $ref: '#/components/schemas/User'
    UserOutDto:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            id:
              type: number
              format: int64
              description: Identificador del usuario
              example: 12
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Código de error
        message:
          type: string
          description: Descripción del error
    BadRequest:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
        - type: object
          properties:
            errorMessages:
              type: array
              items:
                $ref: '#/components/schemas/ErrorMessage'
      example:
        code: 400
        message: Bad Request
    ErrorMessage:
      type: object
      properties:
        fieldName:
          type: string
          description: Campo del error
          example: model
        message:
          type: string
          description: Mensaje de error asociado al campo
          example: El dato es obligatorio
    NotFound:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 404
        message: Not Found
    InternalServerError:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        code: 500
        message: Internal Server Error
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequest'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFound'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerError'